from datetime import datetime
from io import BytesIO
from typing import Any

from app.db.models import Setup


class ExportService:
    """Service for exporting setup data to various formats."""

    async def generate_pdf(
        self,
        setup: Setup,
        include_prices: bool = True,
        include_recommendations: bool = True,
        include_alternatives: bool = False,
    ) -> bytes:
        """Generate a PDF document for the setup."""
        try:
            from weasyprint import HTML, CSS
        except ImportError:
            # Fallback to simple text-based PDF if WeasyPrint not available
            return await self._generate_simple_pdf(
                setup, include_prices, include_recommendations
            )

        html_content = self._build_pdf_html(
            setup, include_prices, include_recommendations, include_alternatives
        )

        # Generate PDF from HTML
        html = HTML(string=html_content)
        css = CSS(string=self._get_pdf_styles())

        pdf_bytes = html.write_pdf(stylesheets=[css])
        return pdf_bytes

    async def _generate_simple_pdf(
        self,
        setup: Setup,
        include_prices: bool,
        include_recommendations: bool,
    ) -> bytes:
        """Generate a simple text-based PDF without WeasyPrint."""
        # Create a simple text representation
        content = self._build_text_content(setup, include_prices, include_recommendations)

        # Return as UTF-8 bytes (caller can handle as text file)
        return content.encode("utf-8")

    def _build_pdf_html(
        self,
        setup: Setup,
        include_prices: bool,
        include_recommendations: bool,
        include_alternatives: bool,
    ) -> str:
        """Build HTML content for PDF generation."""
        profile = setup.wizard_profile or {}
        recommendations = setup.recommendations or {}

        html = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>SO-101 Setup - {setup.id}</title>
</head>
<body>
    <header>
        <h1>SO-101 Robot Arm Setup</h1>
        <p class="date">Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}</p>
        <p class="setup-id">Setup ID: {setup.id}</p>
    </header>

    <section class="profile">
        <h2>Build Profile</h2>
        <table>
            <tr><td>Experience Level</td><td>{profile.get('experience', 'Not specified')}</td></tr>
            <tr><td>Budget</td><td>${profile.get('budget', 'Not specified')}</td></tr>
            <tr><td>Use Case</td><td>{profile.get('use_case', 'Not specified')}</td></tr>
            <tr><td>Compute Platform</td><td>{profile.get('compute_platform', 'Not specified')}</td></tr>
            <tr><td>Camera Preference</td><td>{profile.get('camera_preference', 'Not specified')}</td></tr>
            <tr><td>Arm Type</td><td>{setup.arm_type}</td></tr>
        </table>
    </section>
"""

        if include_recommendations and recommendations:
            html += """
    <section class="recommendations">
        <h2>Recommended Components</h2>
"""
            if recommendations.get("summary"):
                html += f"<p class='summary'>{recommendations['summary']}</p>"

            html += "<table class='components'>"
            html += "<tr><th>Component</th><th>Category</th><th>Qty</th><th>Priority</th><th>Reason</th></tr>"

            for comp in recommendations.get("components", []):
                html += f"""
            <tr>
                <td>{comp.get('component_name', 'Unknown')}</td>
                <td>{comp.get('category', '-')}</td>
                <td>{comp.get('quantity', 1)}</td>
                <td>{comp.get('priority', 'recommended')}</td>
                <td>{comp.get('reason', '-')}</td>
            </tr>
"""
            html += "</table>"

            if recommendations.get("notes"):
                html += "<h3>Notes</h3><ul>"
                for note in recommendations["notes"]:
                    html += f"<li>{note}</li>"
                html += "</ul>"

            html += "</section>"

        # Add setup components if any
        if setup.components:
            html += """
    <section class="setup-components">
        <h2>Selected Components</h2>
        <table>
            <tr><th>Component</th><th>Quantity</th><th>Notes</th></tr>
"""
            for sc in setup.components:
                html += f"""
            <tr>
                <td>Component #{sc.component_id}</td>
                <td>{sc.quantity}</td>
                <td>{sc.notes or '-'}</td>
            </tr>
"""
            html += "</table></section>"

        html += """
    <footer>
        <p>Generated by SO-101 Setup Builder</p>
        <p>LeRobot: <a href="https://github.com/huggingface/lerobot">https://github.com/huggingface/lerobot</a></p>
    </footer>
</body>
</html>
"""
        return html

    def _get_pdf_styles(self) -> str:
        """Get CSS styles for PDF."""
        return """
@page {
    size: A4;
    margin: 2cm;
}

body {
    font-family: 'Helvetica', 'Arial', sans-serif;
    font-size: 11pt;
    line-height: 1.4;
    color: #333;
}

header {
    border-bottom: 2px solid #2563eb;
    padding-bottom: 1em;
    margin-bottom: 2em;
}

h1 {
    color: #1e40af;
    font-size: 24pt;
    margin-bottom: 0.5em;
}

h2 {
    color: #1e40af;
    font-size: 16pt;
    border-bottom: 1px solid #ddd;
    padding-bottom: 0.3em;
    margin-top: 1.5em;
}

h3 {
    color: #374151;
    font-size: 13pt;
}

.date, .setup-id {
    color: #6b7280;
    font-size: 10pt;
}

table {
    width: 100%;
    border-collapse: collapse;
    margin: 1em 0;
}

th, td {
    border: 1px solid #e5e7eb;
    padding: 8px 12px;
    text-align: left;
}

th {
    background-color: #f3f4f6;
    font-weight: bold;
}

tr:nth-child(even) {
    background-color: #f9fafb;
}

.summary {
    background-color: #eff6ff;
    padding: 1em;
    border-left: 4px solid #2563eb;
    margin: 1em 0;
}

ul {
    padding-left: 1.5em;
}

li {
    margin: 0.5em 0;
}

footer {
    margin-top: 3em;
    padding-top: 1em;
    border-top: 1px solid #ddd;
    font-size: 9pt;
    color: #6b7280;
}

footer a {
    color: #2563eb;
}
"""

    def _build_text_content(
        self,
        setup: Setup,
        include_prices: bool,
        include_recommendations: bool,
    ) -> str:
        """Build plain text content."""
        profile = setup.wizard_profile or {}
        recommendations = setup.recommendations or {}

        lines = [
            "=" * 60,
            "SO-101 ROBOT ARM SETUP",
            "=" * 60,
            "",
            f"Setup ID: {setup.id}",
            f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
            "",
            "-" * 40,
            "BUILD PROFILE",
            "-" * 40,
            f"Experience Level: {profile.get('experience', 'Not specified')}",
            f"Budget: ${profile.get('budget', 'Not specified')}",
            f"Use Case: {profile.get('use_case', 'Not specified')}",
            f"Compute Platform: {profile.get('compute_platform', 'Not specified')}",
            f"Camera Preference: {profile.get('camera_preference', 'Not specified')}",
            f"Arm Type: {setup.arm_type}",
            "",
        ]

        if include_recommendations and recommendations:
            lines.extend([
                "-" * 40,
                "RECOMMENDED COMPONENTS",
                "-" * 40,
            ])

            if recommendations.get("summary"):
                lines.extend(["", recommendations["summary"], ""])

            for comp in recommendations.get("components", []):
                lines.append(
                    f"- {comp.get('component_name', 'Unknown')} "
                    f"(x{comp.get('quantity', 1)}) - {comp.get('priority', 'recommended')}"
                )
                if comp.get("reason"):
                    lines.append(f"  Reason: {comp['reason']}")

            if recommendations.get("notes"):
                lines.extend(["", "Notes:"])
                for note in recommendations["notes"]:
                    lines.append(f"  * {note}")

        lines.extend([
            "",
            "-" * 40,
            "Generated by SO-101 Setup Builder",
            "LeRobot: https://github.com/huggingface/lerobot",
            "-" * 40,
        ])

        return "\n".join(lines)
